backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: ./src/images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
